---
title: "TidyTuesday 2019/22 - Wine Ratings by Vivino"
author: "Cedric Scherer"
date: "28th of May 2019"
output:
  html_document:
    theme: paper
    highlight: kate
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

```{r prep, message=FALSE}
## packages
library(tidyverse)
library(patchwork)

library(ggplot2)

if ("extrafont" %in% rownames(installed.packages()))
{
  library(extrafont)
  #extrafont::font_import()
  extrafont::loadfonts(device = "pdf", quiet = TRUE)
  base <- "Poppins"
} else {
  base <- "Gadugi"   
}

theme_custom <- function (base_size = 12, base_family = base)
{
  half_line <- base_size/2
  theme(line = element_line(colour = "grey85", size = 0.4, linetype = 1, lineend = "butt"), 
        rect = element_rect(fill = "grey20", colour = "grey85", size = 0.4, linetype = 1), 
        text = element_text(family = base_family, face = "plain", colour = "white", size = base_size, 
                            lineheight = 0.9, hjust = 0.5, vjust = 0.5, angle = 0, margin = margin(),  debug = FALSE), 
        axis.line = element_blank(), 
        axis.line.x = NULL, 
        axis.line.y = NULL, 
        axis.text = element_text(size = base_size * 1.1, colour = "grey85"), 
        axis.text.x = element_text(margin = margin(t = 0.8 * half_line/2), vjust = 1), 
        axis.text.x.top = element_text(margin = margin(b = 0.8 * half_line/2), vjust = 0), 
        axis.text.y = element_text(margin = margin(r = 0.8 * half_line/2), hjust = 1), 
        axis.text.y.right = element_text(margin = margin(l = 0.8 * half_line/2), hjust = 0), 
        axis.ticks = element_line(colour = "grey85", size = 0.3), 
        axis.ticks.length = unit(half_line/2, "pt"), 
        axis.ticks.length.x = NULL, 
        axis.ticks.length.x.top = NULL, 
        axis.ticks.length.x.bottom = NULL, 
        axis.ticks.length.y = NULL, 
        axis.ticks.length.y.left = NULL, 
        axis.ticks.length.y.right = NULL, 
        axis.title.x = element_text(margin = unit(c(3.5, 0, 0, 0), "mm"), vjust = 1, size = base_size * 1.3, face = "bold"), 
        axis.title.x.top = element_text(margin = margin(b = half_line), vjust = 0), 
        axis.title.y = element_text(angle = 90, margin = unit(c(0, 3.5, 0, 0), "mm"), vjust = 1, size = base_size * 1.3, face = "bold"), 
        axis.title.y.right = element_text(angle = -90, margin = margin(l = half_line), vjust = 0), 
        legend.background = element_rect(colour = NA), 
        legend.spacing = unit(0.4, "cm"), 
        legend.spacing.x = NULL, 
        legend.spacing.y = NULL, 
        legend.margin = margin(0.2, 0.2, 0.2, 0.2, "cm"), 
        legend.key = element_rect(fill = "grey20", colour = "grey20"), 
        legend.key.size = unit(1.2, "lines"), 
        legend.key.height = NULL, 
        legend.key.width = NULL, 
        legend.text = element_text(size = rel(0.9)), 
        legend.text.align = NULL, 
        legend.title = element_text(hjust = 0, size = rel(1)), 
        legend.title.align = NULL, 
        legend.position = "right", 
        legend.direction = NULL, 
        legend.justification = "center", 
        legend.box = NULL, 
        legend.box.margin = margin(0, 0, 0, 0, "cm"), 
        legend.box.background = element_blank(), 
        legend.box.spacing = unit(0.4, "cm"), 
        panel.background = element_rect(fill = NA, colour = NA), 
        panel.border = element_rect(colour = "grey85", fill = NA, size = rel(1)),
        panel.grid = element_blank(),
        panel.grid.major = element_line(colour = "transparent"), 
        panel.grid.minor = element_line(colour = "transparent"), 
        panel.spacing = unit(base_size/2, "pt"), 
        panel.spacing.x = NULL, 
        panel.spacing.y = NULL, 
        panel.ontop = FALSE, 
        strip.background = element_rect(fill = "grey20", colour = "grey85"), 
        strip.text = element_text(colour = "white", size = base_size * 1.1, face = "bold"), 
        strip.text.x = element_text(margin = margin(t = half_line, b = half_line)), 
        strip.text.y = element_text(angle = -90, margin = margin(l = half_line, r = half_line)), 
        strip.placement = "inside", 
        strip.placement.x = NULL, 
        strip.placement.y = NULL, 
        strip.switch.pad.grid = unit(0.1, "cm"), 
        strip.switch.pad.wrap = unit(0.1, "cm"), 
        plot.background = element_rect(colour = NA), 
        plot.title = element_text(size = base_size * 1.8, hjust = 0, vjust = 1, face = "bold", margin = margin(b = half_line * 1.2)), 
        plot.subtitle = element_text(size = base_size, hjust = 0, vjust = 1, margin = margin(b = half_line * 0.9)), 
        plot.caption = element_text(size = rel(0.9), hjust = 1, vjust = 1, margin = margin(t = half_line * 0.9), color = "white"), 
        plot.margin = margin(base_size, base_size, base_size, base_size), complete = T,
        plot.tag = element_text(size = rel(1.5), face = "bold", hjust = 0.5, vjust = 0.5), 
        plot.tag.position = "topleft")
}

theme_set(theme_custom())
```

```{r data}
df_wines <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-28/winemag-data-130k-v2.csv") %>% 
  dplyr::select(-X1) %>% 
  unique()
```

```{r data-top-countries}
df_wines_top_countries <- df_wines %>% 
  group_by(country) %>% 
  summarize(
    rating = mean(points, na.rm = T),
    n = n()
  ) %>% 
  mutate(rating = (rating - 80) / 20) %>% 
  filter(
    !is.na(country),
    n > 99
  ) %>%
  top_n(6, rating)
```


```{r plot}
img_b <- png::readPNG("bottle.png") 
bottle <- grid::rasterGrob(img_b, interpolate = T) 

bottles <- df_wines_top_countries  %>% 
  mutate(country = fct_reorder(country, -rating)) %>% 
  ggplot(aes(country, rating)) +
    geom_col(width = 12, fill = "#770000") +
    annotation_custom(bottle, xmin = -24, xmax = 26, ymin = 0, ymax = 1.3) +
    facet_wrap(~ country, nrow = 1, scales = "free_x", strip.position = "bottom") +
    scale_x_discrete(expand = c(10, 10)) +
    scale_y_continuous(limits = c(0, 1.3), breaks = seq(0, 1, by = 0.25), 
                       labels = c("80", "85", "90", "95", "100")) +
    theme(plot.caption = element_text(size = 9),
          plot.margin = margin(0, 0, 0, 0),
          axis.title.y = element_text(size = 14, hjust = 0.3),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 14, family = "Roboto Mono"),
          axis.ticks = element_blank(),
          strip.background = element_rect(color = NA),
          strip.text = element_text(size = 16, vjust = 1),
          panel.border = element_rect(color = NA),
          panel.grid.major.y = element_line(color = "grey30"),
          panel.spacing = unit(0, "lines")) +
  labs(x = NULL, y = "Rating", title = NULL, subtitle = NULL)
```

```{r}
words <- df_wines %>% 
  group_by(country) %>% 
  mutate(rating = mean(points, na.rm = T)) %>% 
  filter(country %in% df_wines_top_countries$country) %>%
  ungroup() %>% 
  mutate(country = fct_reorder(country, -rating)) %>% 
  group_by(country, variety) %>% 
  summarize(
    rating = mean(points, na.rm = T),
    count = n()
  ) %>% 
  arrange(-rating, -count) %>% 
  slice(1:5) %>% 
  mutate(id = row_number()) %>% 
  dplyr::select(-rating, -count) %>% 
  spread(id, variety) %>% 
  ggplot() +
    geom_text(aes(x = 5, y = 5, label = `1`), size = 3.5, family = "Poppins", color = "#fff8f8") + 
    geom_text(aes(x = 5, y = 4, label = `2`), size = 3.5, family = "Poppins", color = "#ffc5c5") + 
    geom_text(aes(x = 5, y = 3, label = `3`), size = 3.5, family = "Poppins", color = "#ff7878") + 
    geom_text(aes(x = 5, y = 2, label = `4`), size = 3.5, family = "Poppins", color = "#ff2b2b") + 
    geom_text(aes(x = 5, y = 1, label = `5`), size = 3.5, family = "Poppins", color = "#c40000") + 
    facet_wrap(~ country, nrow = 1, scales = "free_y") +
    theme(strip.text = element_blank(),
          axis.text = element_blank(),
          axis.title = element_blank(),
          panel.border = element_rect(color = "transparent"),
          panel.spacing = unit(0, "lines"),
          axis.ticks = element_blank()) +
    labs(caption = "\nVisualization by Cédric Scherer  |  Data source: Kaggle")
```

```{r title}
## left-alligned title
title <- ggplot(data.frame(x = 1:2, y = 1:10)) +
  labs(x = NULL, y = NULL,
       title = "The best wines you can get.",
       subtitle = "Highest average rating for countries with \u2265 100 wines and their 5 highest rated varieties listed on Vivino  (based on reviews with 80 points or more).\n") +
  theme(line = element_blank(),
        plot.background = element_rect(fill = "transparent", color = "transparent"),
        panel.background = element_rect(fill = "transparent"),
        panel.border = element_rect(color = "transparent"),
        axis.text = element_blank())
```

```{r full-panel, fig.width = 14, fig.height = 5.3}
title + 
  (bottles + words + plot_layout(heights = c(1, 0.45), ncol = 1)) + 
  plot_layout(widths = c(0, 1))

```

***

```{r}
sessionInfo()
```
